name: Packer file to install

on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PKR_VAR_DATABASEUSER: ${{ secrets.DATABASEUSER }}
      PKR_VAR_DATABASEPASSWORD: ${{ secrets.DATABASEPASSWORD }}
      PKR_VAR_DATABASEHOST: ${{ secrets.DATABASEHOST }}
      PKR_VAR_DBPORT: ${{ secrets.DBPORT }}
      PKR_VAR_PORT: ${{ secrets.PORT }}
      PKR_VAR_DATABASE: ${{ secrets.DATABASE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Create zip archive
        run: zip -r webapp.zip .
      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install -y packer
      - name: Packer Init
        run: packer init packer
      - name: Packer Build - Branches
        run: packer build packer
