name: CI

on:
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install jest
      - run: npm run test
      - name: Create zip archive
        run: zip -r webapp.zip .

  packer-build:
    name: Packer Build
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      PKR_VAR_MYSQL_USER: ${{ secrets.DATABASEUSER }}
      PKR_VAR_MYSQL_PASSWORD: ${{ secrets.DATABASEPASSWORD }}
      PKR_VAR_MYSQL_HOST: ${{ secrets.DATABASEHOST }}
      PKR_VAR_MYSQL_PORT: ${{ secrets.PORT }}
      PKR_VAR_MYSQL_DB: ${{ secrets.DATABASE }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Packer
      run: sudo apt-get update && sudo apt-get install -y packer
    - name: Initialize packer
      run: packer init .
    - name: Build Packer image
      run: packer build .
      
