name: CI

on:
  pull_request:
    branches: [main]
permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-version: [16.x]
    
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm install jest
      - run: npm run test
      - name: Create zip archive
        run: zip -r webapp.zip .
        # uses: vimtor/action-zip@v1
        # with:
        #   path: dist
        #   format: zip
        #   destination: dist/build/webapp.zip
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Packer Init
        run: packer init .
      - name: Packer Build - Branches
        run: packer build .
